services:
    qbittorrent: # qB下载器
        image: lscr.io/linuxserver/qbittorrent:latest   # 镜像名称
        container_name: qbittorrent    #容器名，可自定义
        restart: unless-stopped    #启动选项
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Asia/Shanghai # 上海时区
            - UMASK_SET=022
            - WEBUI_PORT=8081 # 此处修改WEB 管理平台端口 
            - TORRENTING_PORT=6881
        volumes:
            - ./config:/config # 绝对路径请修改为自己的config文件夹
            - /mnt/ARS2-NFS/downloads/qbittorrent:/downloads # 绝对路径请修改为自己的downloads文件夹
        ports:
            # 要使用的映射下载端口与内部下载端口，可保持默认，安装完成后在管理页面仍然可以改成其他端口。
            - 6881:6881
            - 6881:6881/udp
            - 8081:8081 # 此处WEB UI 目标端口与内部端口务必保证相同，见问题1
        network_mode: bridge   # 使用桥接网络模式
 
# ssh查看随机密码：docker logs qbittorrent