services:
   nascab: ## 服务名称（可自定义）
      container_name: nascab ## 定义容器名称
      image: ypptec/nascab:3.5.3-x64 ## 镜像版本
      restart: always ## 重启策略
      network_mode: bridge ## 桥接网络
      ports:
         - 5388:80
         - 5343:443
         - 5390:90
         - 5321:21
      volumes:
         - ./config:/root/.local/share/nascab   ## 映射nascab配置文件目录
         - /mnt:/mnt