services:
     pms-docker:
          container_name: plex
          ports:
               - 32400:32400/tcp
               - 8324:8324/tcp
               - 32469:32469/tcp
               - 1900:1900/udp
               - 32410:32410/udp
               - 32412:32412/udp
               - 32413:32413/udp
               - 32414:32414/udp
          environment:
               - TZ=Asia/Shanghai
               ## 获取PLEX_CLAIM地址：https://www.plex.tv/claim
               - PLEX_CLAIM=claim-L4apnTB__5UU9Xa1wvUB
               - ADVERTISE_IP=http://10.10.10.245:32400/

          ## 定义服务器名称-随意
          hostname: <plex>
          volumes:
               - ./config:/config
               - ./transcode:/transcode
               - /mnt/ARS2-NFS/nas/link:/data
               - /mnt:/mnt:rslave
          image: plexinc/pms-docker
