services:
   nginx: ## 服务名称（可自定义）
      container_name: nginx ## 容器名称（可自定义）
      image: nginx ## 镜像版本
      restart: always ## 重启策略
      network_mode: bridge ## 桥接网络
      ports:
         - 85:80
         - 5553:443
      volumes:
         - ./keyfile:/etc/nginx/keyfile ## 密钥文件
         - ./conf.d:/etc/nginx/conf.d ## 配置文件目录
         - ./html:/usr/share/nginx/html
         - ./logs:/var/log/nginx
         - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      environment:
         - TZ=Asia/Shanghai
      privileged: true
