services:
   xiaomusic:
      image: m.daocloud.io/docker.io/hanxi/xiaomusic ## 国内镜像名称
      ## image: hanxi/xiaomusic ## 国外镜像名称
      container_name: xiaomusic ## 容器名称（可修改）
      restart: unless-stopped ## 重启策略
      ports:
         - 8393:8090 ## 端口映射
      volumes:
         - /mnt/file/music:/app/music ## 本地歌曲路径
         - ./conf:/app/conf ## 配置文件路径
      environment:
        XIAOMUSIC_PUBLIC_PORT: 8393